/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PendingApprovalRouteImport } from './routes/pending-approval'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDriverRouteImport } from './routes/_authenticated/driver'
import { Route as AuthenticatedDispatcherRouteImport } from './routes/_authenticated/_dispatcher'
import { Route as AuthenticatedCrmRouteImport } from './routes/_authenticated/_crm'
import { Route as AuthenticatedDriverIndexRouteImport } from './routes/_authenticated/driver/index'
import { Route as AuthenticatedDispatcherVehiclesRouteImport } from './routes/_authenticated/_dispatcher/vehicles'
import { Route as AuthenticatedDispatcherUsersRouteImport } from './routes/_authenticated/_dispatcher/users'
import { Route as AuthenticatedDispatcherSettingsRouteImport } from './routes/_authenticated/_dispatcher/settings'
import { Route as AuthenticatedDispatcherReportsRouteImport } from './routes/_authenticated/_dispatcher/reports'
import { Route as AuthenticatedDispatcherMapRouteImport } from './routes/_authenticated/_dispatcher/map'
import { Route as AuthenticatedDispatcherFacilitiesRouteImport } from './routes/_authenticated/_dispatcher/facilities'
import { Route as AuthenticatedDispatcherDriversRouteImport } from './routes/_authenticated/_dispatcher/drivers'
import { Route as AuthenticatedDispatcherDashboardRouteImport } from './routes/_authenticated/_dispatcher/dashboard'
import { Route as AuthenticatedDispatcherAuditLogRouteImport } from './routes/_authenticated/_dispatcher/audit-log'
import { Route as AuthenticatedDispatcherCasesIndexRouteImport } from './routes/_authenticated/_dispatcher/cases.index'
import { Route as AuthenticatedCrmCrmIndexRouteImport } from './routes/_authenticated/_crm/crm.index'
import { Route as AuthenticatedCasesCaseIdPrintRouteImport } from './routes/_authenticated/cases.$caseId.print'
import { Route as AuthenticatedDispatcherCasesNewRouteImport } from './routes/_authenticated/_dispatcher/cases.new'
import { Route as AuthenticatedDispatcherCasesCaseIdRouteImport } from './routes/_authenticated/_dispatcher/cases.$caseId'
import { Route as AuthenticatedCrmCrmUsersRouteImport } from './routes/_authenticated/_crm/crm.users'
import { Route as AuthenticatedCrmCrmUpdatesRouteImport } from './routes/_authenticated/_crm/crm.updates'
import { Route as AuthenticatedCrmCrmReportsRouteImport } from './routes/_authenticated/_crm/crm.reports'
import { Route as AuthenticatedCrmCrmFuneralHomesRouteImport } from './routes/_authenticated/_crm/crm.funeral-homes'
import { Route as AuthenticatedCrmCrmExportAuditRouteImport } from './routes/_authenticated/_crm/crm.export-audit'
import { Route as AuthenticatedCrmCrmDecedentsRouteImport } from './routes/_authenticated/_crm/crm.decedents'
import { Route as AuthenticatedCrmCrmDashboardRouteImport } from './routes/_authenticated/_crm/crm.dashboard'
import { Route as AuthenticatedCrmCrmCremationLogsRouteImport } from './routes/_authenticated/_crm/crm.cremation-logs'
import { Route as AuthenticatedCrmCrmCremationLogsLogIdPrintRouteImport } from './routes/_authenticated/_crm/crm.cremation-logs.$logId.print'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingApprovalRoute = PendingApprovalRouteImport.update({
  id: '/pending-approval',
  path: '/pending-approval',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDriverRoute = AuthenticatedDriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDispatcherRoute = AuthenticatedDispatcherRouteImport.update({
  id: '/_dispatcher',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCrmRoute = AuthenticatedCrmRouteImport.update({
  id: '/_crm',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDriverIndexRoute =
  AuthenticatedDriverIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDriverRoute,
  } as any)
const AuthenticatedDispatcherVehiclesRoute =
  AuthenticatedDispatcherVehiclesRouteImport.update({
    id: '/vehicles',
    path: '/vehicles',
    getParentRoute: () => AuthenticatedDispatcherRoute,
  } as any)
const AuthenticatedDispatcherUsersRoute =
  AuthenticatedDispatcherUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedDispatcherRoute,
  } as any)
const AuthenticatedDispatcherSettingsRoute =
  AuthenticatedDispatcherSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedDispatcherRoute,
  } as any)
const AuthenticatedDispatcherReportsRoute =
  AuthenticatedDispatcherReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedDispatcherRoute,
  } as any)
const AuthenticatedDispatcherMapRoute =
  AuthenticatedDispatcherMapRouteImport.update({
    id: '/map',
    path: '/map',
    getParentRoute: () => AuthenticatedDispatcherRoute,
  } as any)
const AuthenticatedDispatcherFacilitiesRoute =
  AuthenticatedDispatcherFacilitiesRouteImport.update({
    id: '/facilities',
    path: '/facilities',
    getParentRoute: () => AuthenticatedDispatcherRoute,
  } as any)
const AuthenticatedDispatcherDriversRoute =
  AuthenticatedDispatcherDriversRouteImport.update({
    id: '/drivers',
    path: '/drivers',
    getParentRoute: () => AuthenticatedDispatcherRoute,
  } as any)
const AuthenticatedDispatcherDashboardRoute =
  AuthenticatedDispatcherDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedDispatcherRoute,
  } as any)
const AuthenticatedDispatcherAuditLogRoute =
  AuthenticatedDispatcherAuditLogRouteImport.update({
    id: '/audit-log',
    path: '/audit-log',
    getParentRoute: () => AuthenticatedDispatcherRoute,
  } as any)
const AuthenticatedDispatcherCasesIndexRoute =
  AuthenticatedDispatcherCasesIndexRouteImport.update({
    id: '/cases/',
    path: '/cases/',
    getParentRoute: () => AuthenticatedDispatcherRoute,
  } as any)
const AuthenticatedCrmCrmIndexRoute =
  AuthenticatedCrmCrmIndexRouteImport.update({
    id: '/crm/',
    path: '/crm/',
    getParentRoute: () => AuthenticatedCrmRoute,
  } as any)
const AuthenticatedCasesCaseIdPrintRoute =
  AuthenticatedCasesCaseIdPrintRouteImport.update({
    id: '/cases/$caseId/print',
    path: '/cases/$caseId/print',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDispatcherCasesNewRoute =
  AuthenticatedDispatcherCasesNewRouteImport.update({
    id: '/cases/new',
    path: '/cases/new',
    getParentRoute: () => AuthenticatedDispatcherRoute,
  } as any)
const AuthenticatedDispatcherCasesCaseIdRoute =
  AuthenticatedDispatcherCasesCaseIdRouteImport.update({
    id: '/cases/$caseId',
    path: '/cases/$caseId',
    getParentRoute: () => AuthenticatedDispatcherRoute,
  } as any)
const AuthenticatedCrmCrmUsersRoute =
  AuthenticatedCrmCrmUsersRouteImport.update({
    id: '/crm/users',
    path: '/crm/users',
    getParentRoute: () => AuthenticatedCrmRoute,
  } as any)
const AuthenticatedCrmCrmUpdatesRoute =
  AuthenticatedCrmCrmUpdatesRouteImport.update({
    id: '/crm/updates',
    path: '/crm/updates',
    getParentRoute: () => AuthenticatedCrmRoute,
  } as any)
const AuthenticatedCrmCrmReportsRoute =
  AuthenticatedCrmCrmReportsRouteImport.update({
    id: '/crm/reports',
    path: '/crm/reports',
    getParentRoute: () => AuthenticatedCrmRoute,
  } as any)
const AuthenticatedCrmCrmFuneralHomesRoute =
  AuthenticatedCrmCrmFuneralHomesRouteImport.update({
    id: '/crm/funeral-homes',
    path: '/crm/funeral-homes',
    getParentRoute: () => AuthenticatedCrmRoute,
  } as any)
const AuthenticatedCrmCrmExportAuditRoute =
  AuthenticatedCrmCrmExportAuditRouteImport.update({
    id: '/crm/export-audit',
    path: '/crm/export-audit',
    getParentRoute: () => AuthenticatedCrmRoute,
  } as any)
const AuthenticatedCrmCrmDecedentsRoute =
  AuthenticatedCrmCrmDecedentsRouteImport.update({
    id: '/crm/decedents',
    path: '/crm/decedents',
    getParentRoute: () => AuthenticatedCrmRoute,
  } as any)
const AuthenticatedCrmCrmDashboardRoute =
  AuthenticatedCrmCrmDashboardRouteImport.update({
    id: '/crm/dashboard',
    path: '/crm/dashboard',
    getParentRoute: () => AuthenticatedCrmRoute,
  } as any)
const AuthenticatedCrmCrmCremationLogsRoute =
  AuthenticatedCrmCrmCremationLogsRouteImport.update({
    id: '/crm/cremation-logs',
    path: '/crm/cremation-logs',
    getParentRoute: () => AuthenticatedCrmRoute,
  } as any)
const AuthenticatedCrmCrmCremationLogsLogIdPrintRoute =
  AuthenticatedCrmCrmCremationLogsLogIdPrintRouteImport.update({
    id: '/$logId/print',
    path: '/$logId/print',
    getParentRoute: () => AuthenticatedCrmCrmCremationLogsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/reset-password': typeof ResetPasswordRoute
  '/driver': typeof AuthenticatedDriverRouteWithChildren
  '/audit-log': typeof AuthenticatedDispatcherAuditLogRoute
  '/dashboard': typeof AuthenticatedDispatcherDashboardRoute
  '/drivers': typeof AuthenticatedDispatcherDriversRoute
  '/facilities': typeof AuthenticatedDispatcherFacilitiesRoute
  '/map': typeof AuthenticatedDispatcherMapRoute
  '/reports': typeof AuthenticatedDispatcherReportsRoute
  '/settings': typeof AuthenticatedDispatcherSettingsRoute
  '/users': typeof AuthenticatedDispatcherUsersRoute
  '/vehicles': typeof AuthenticatedDispatcherVehiclesRoute
  '/driver/': typeof AuthenticatedDriverIndexRoute
  '/crm/cremation-logs': typeof AuthenticatedCrmCrmCremationLogsRouteWithChildren
  '/crm/dashboard': typeof AuthenticatedCrmCrmDashboardRoute
  '/crm/decedents': typeof AuthenticatedCrmCrmDecedentsRoute
  '/crm/export-audit': typeof AuthenticatedCrmCrmExportAuditRoute
  '/crm/funeral-homes': typeof AuthenticatedCrmCrmFuneralHomesRoute
  '/crm/reports': typeof AuthenticatedCrmCrmReportsRoute
  '/crm/updates': typeof AuthenticatedCrmCrmUpdatesRoute
  '/crm/users': typeof AuthenticatedCrmCrmUsersRoute
  '/cases/$caseId': typeof AuthenticatedDispatcherCasesCaseIdRoute
  '/cases/new': typeof AuthenticatedDispatcherCasesNewRoute
  '/cases/$caseId/print': typeof AuthenticatedCasesCaseIdPrintRoute
  '/crm/': typeof AuthenticatedCrmCrmIndexRoute
  '/cases/': typeof AuthenticatedDispatcherCasesIndexRoute
  '/crm/cremation-logs/$logId/print': typeof AuthenticatedCrmCrmCremationLogsLogIdPrintRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/reset-password': typeof ResetPasswordRoute
  '/audit-log': typeof AuthenticatedDispatcherAuditLogRoute
  '/dashboard': typeof AuthenticatedDispatcherDashboardRoute
  '/drivers': typeof AuthenticatedDispatcherDriversRoute
  '/facilities': typeof AuthenticatedDispatcherFacilitiesRoute
  '/map': typeof AuthenticatedDispatcherMapRoute
  '/reports': typeof AuthenticatedDispatcherReportsRoute
  '/settings': typeof AuthenticatedDispatcherSettingsRoute
  '/users': typeof AuthenticatedDispatcherUsersRoute
  '/vehicles': typeof AuthenticatedDispatcherVehiclesRoute
  '/driver': typeof AuthenticatedDriverIndexRoute
  '/crm/cremation-logs': typeof AuthenticatedCrmCrmCremationLogsRouteWithChildren
  '/crm/dashboard': typeof AuthenticatedCrmCrmDashboardRoute
  '/crm/decedents': typeof AuthenticatedCrmCrmDecedentsRoute
  '/crm/export-audit': typeof AuthenticatedCrmCrmExportAuditRoute
  '/crm/funeral-homes': typeof AuthenticatedCrmCrmFuneralHomesRoute
  '/crm/reports': typeof AuthenticatedCrmCrmReportsRoute
  '/crm/updates': typeof AuthenticatedCrmCrmUpdatesRoute
  '/crm/users': typeof AuthenticatedCrmCrmUsersRoute
  '/cases/$caseId': typeof AuthenticatedDispatcherCasesCaseIdRoute
  '/cases/new': typeof AuthenticatedDispatcherCasesNewRoute
  '/cases/$caseId/print': typeof AuthenticatedCasesCaseIdPrintRoute
  '/crm': typeof AuthenticatedCrmCrmIndexRoute
  '/cases': typeof AuthenticatedDispatcherCasesIndexRoute
  '/crm/cremation-logs/$logId/print': typeof AuthenticatedCrmCrmCremationLogsLogIdPrintRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/_crm': typeof AuthenticatedCrmRouteWithChildren
  '/_authenticated/_dispatcher': typeof AuthenticatedDispatcherRouteWithChildren
  '/_authenticated/driver': typeof AuthenticatedDriverRouteWithChildren
  '/_authenticated/_dispatcher/audit-log': typeof AuthenticatedDispatcherAuditLogRoute
  '/_authenticated/_dispatcher/dashboard': typeof AuthenticatedDispatcherDashboardRoute
  '/_authenticated/_dispatcher/drivers': typeof AuthenticatedDispatcherDriversRoute
  '/_authenticated/_dispatcher/facilities': typeof AuthenticatedDispatcherFacilitiesRoute
  '/_authenticated/_dispatcher/map': typeof AuthenticatedDispatcherMapRoute
  '/_authenticated/_dispatcher/reports': typeof AuthenticatedDispatcherReportsRoute
  '/_authenticated/_dispatcher/settings': typeof AuthenticatedDispatcherSettingsRoute
  '/_authenticated/_dispatcher/users': typeof AuthenticatedDispatcherUsersRoute
  '/_authenticated/_dispatcher/vehicles': typeof AuthenticatedDispatcherVehiclesRoute
  '/_authenticated/driver/': typeof AuthenticatedDriverIndexRoute
  '/_authenticated/_crm/crm/cremation-logs': typeof AuthenticatedCrmCrmCremationLogsRouteWithChildren
  '/_authenticated/_crm/crm/dashboard': typeof AuthenticatedCrmCrmDashboardRoute
  '/_authenticated/_crm/crm/decedents': typeof AuthenticatedCrmCrmDecedentsRoute
  '/_authenticated/_crm/crm/export-audit': typeof AuthenticatedCrmCrmExportAuditRoute
  '/_authenticated/_crm/crm/funeral-homes': typeof AuthenticatedCrmCrmFuneralHomesRoute
  '/_authenticated/_crm/crm/reports': typeof AuthenticatedCrmCrmReportsRoute
  '/_authenticated/_crm/crm/updates': typeof AuthenticatedCrmCrmUpdatesRoute
  '/_authenticated/_crm/crm/users': typeof AuthenticatedCrmCrmUsersRoute
  '/_authenticated/_dispatcher/cases/$caseId': typeof AuthenticatedDispatcherCasesCaseIdRoute
  '/_authenticated/_dispatcher/cases/new': typeof AuthenticatedDispatcherCasesNewRoute
  '/_authenticated/cases/$caseId/print': typeof AuthenticatedCasesCaseIdPrintRoute
  '/_authenticated/_crm/crm/': typeof AuthenticatedCrmCrmIndexRoute
  '/_authenticated/_dispatcher/cases/': typeof AuthenticatedDispatcherCasesIndexRoute
  '/_authenticated/_crm/crm/cremation-logs/$logId/print': typeof AuthenticatedCrmCrmCremationLogsLogIdPrintRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/pending-approval'
    | '/reset-password'
    | '/driver'
    | '/audit-log'
    | '/dashboard'
    | '/drivers'
    | '/facilities'
    | '/map'
    | '/reports'
    | '/settings'
    | '/users'
    | '/vehicles'
    | '/driver/'
    | '/crm/cremation-logs'
    | '/crm/dashboard'
    | '/crm/decedents'
    | '/crm/export-audit'
    | '/crm/funeral-homes'
    | '/crm/reports'
    | '/crm/updates'
    | '/crm/users'
    | '/cases/$caseId'
    | '/cases/new'
    | '/cases/$caseId/print'
    | '/crm/'
    | '/cases/'
    | '/crm/cremation-logs/$logId/print'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/pending-approval'
    | '/reset-password'
    | '/audit-log'
    | '/dashboard'
    | '/drivers'
    | '/facilities'
    | '/map'
    | '/reports'
    | '/settings'
    | '/users'
    | '/vehicles'
    | '/driver'
    | '/crm/cremation-logs'
    | '/crm/dashboard'
    | '/crm/decedents'
    | '/crm/export-audit'
    | '/crm/funeral-homes'
    | '/crm/reports'
    | '/crm/updates'
    | '/crm/users'
    | '/cases/$caseId'
    | '/cases/new'
    | '/cases/$caseId/print'
    | '/crm'
    | '/cases'
    | '/crm/cremation-logs/$logId/print'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/pending-approval'
    | '/reset-password'
    | '/_authenticated/_crm'
    | '/_authenticated/_dispatcher'
    | '/_authenticated/driver'
    | '/_authenticated/_dispatcher/audit-log'
    | '/_authenticated/_dispatcher/dashboard'
    | '/_authenticated/_dispatcher/drivers'
    | '/_authenticated/_dispatcher/facilities'
    | '/_authenticated/_dispatcher/map'
    | '/_authenticated/_dispatcher/reports'
    | '/_authenticated/_dispatcher/settings'
    | '/_authenticated/_dispatcher/users'
    | '/_authenticated/_dispatcher/vehicles'
    | '/_authenticated/driver/'
    | '/_authenticated/_crm/crm/cremation-logs'
    | '/_authenticated/_crm/crm/dashboard'
    | '/_authenticated/_crm/crm/decedents'
    | '/_authenticated/_crm/crm/export-audit'
    | '/_authenticated/_crm/crm/funeral-homes'
    | '/_authenticated/_crm/crm/reports'
    | '/_authenticated/_crm/crm/updates'
    | '/_authenticated/_crm/crm/users'
    | '/_authenticated/_dispatcher/cases/$caseId'
    | '/_authenticated/_dispatcher/cases/new'
    | '/_authenticated/cases/$caseId/print'
    | '/_authenticated/_crm/crm/'
    | '/_authenticated/_dispatcher/cases/'
    | '/_authenticated/_crm/crm/cremation-logs/$logId/print'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PendingApprovalRoute: typeof PendingApprovalRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending-approval': {
      id: '/pending-approval'
      path: '/pending-approval'
      fullPath: '/pending-approval'
      preLoaderRoute: typeof PendingApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/driver': {
      id: '/_authenticated/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof AuthenticatedDriverRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_dispatcher': {
      id: '/_authenticated/_dispatcher'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedDispatcherRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_crm': {
      id: '/_authenticated/_crm'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedCrmRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/driver/': {
      id: '/_authenticated/driver/'
      path: '/'
      fullPath: '/driver/'
      preLoaderRoute: typeof AuthenticatedDriverIndexRouteImport
      parentRoute: typeof AuthenticatedDriverRoute
    }
    '/_authenticated/_dispatcher/vehicles': {
      id: '/_authenticated/_dispatcher/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof AuthenticatedDispatcherVehiclesRouteImport
      parentRoute: typeof AuthenticatedDispatcherRoute
    }
    '/_authenticated/_dispatcher/users': {
      id: '/_authenticated/_dispatcher/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedDispatcherUsersRouteImport
      parentRoute: typeof AuthenticatedDispatcherRoute
    }
    '/_authenticated/_dispatcher/settings': {
      id: '/_authenticated/_dispatcher/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedDispatcherSettingsRouteImport
      parentRoute: typeof AuthenticatedDispatcherRoute
    }
    '/_authenticated/_dispatcher/reports': {
      id: '/_authenticated/_dispatcher/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedDispatcherReportsRouteImport
      parentRoute: typeof AuthenticatedDispatcherRoute
    }
    '/_authenticated/_dispatcher/map': {
      id: '/_authenticated/_dispatcher/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AuthenticatedDispatcherMapRouteImport
      parentRoute: typeof AuthenticatedDispatcherRoute
    }
    '/_authenticated/_dispatcher/facilities': {
      id: '/_authenticated/_dispatcher/facilities'
      path: '/facilities'
      fullPath: '/facilities'
      preLoaderRoute: typeof AuthenticatedDispatcherFacilitiesRouteImport
      parentRoute: typeof AuthenticatedDispatcherRoute
    }
    '/_authenticated/_dispatcher/drivers': {
      id: '/_authenticated/_dispatcher/drivers'
      path: '/drivers'
      fullPath: '/drivers'
      preLoaderRoute: typeof AuthenticatedDispatcherDriversRouteImport
      parentRoute: typeof AuthenticatedDispatcherRoute
    }
    '/_authenticated/_dispatcher/dashboard': {
      id: '/_authenticated/_dispatcher/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDispatcherDashboardRouteImport
      parentRoute: typeof AuthenticatedDispatcherRoute
    }
    '/_authenticated/_dispatcher/audit-log': {
      id: '/_authenticated/_dispatcher/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AuthenticatedDispatcherAuditLogRouteImport
      parentRoute: typeof AuthenticatedDispatcherRoute
    }
    '/_authenticated/_dispatcher/cases/': {
      id: '/_authenticated/_dispatcher/cases/'
      path: '/cases'
      fullPath: '/cases/'
      preLoaderRoute: typeof AuthenticatedDispatcherCasesIndexRouteImport
      parentRoute: typeof AuthenticatedDispatcherRoute
    }
    '/_authenticated/_crm/crm/': {
      id: '/_authenticated/_crm/crm/'
      path: '/crm'
      fullPath: '/crm/'
      preLoaderRoute: typeof AuthenticatedCrmCrmIndexRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/cases/$caseId/print': {
      id: '/_authenticated/cases/$caseId/print'
      path: '/cases/$caseId/print'
      fullPath: '/cases/$caseId/print'
      preLoaderRoute: typeof AuthenticatedCasesCaseIdPrintRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_dispatcher/cases/new': {
      id: '/_authenticated/_dispatcher/cases/new'
      path: '/cases/new'
      fullPath: '/cases/new'
      preLoaderRoute: typeof AuthenticatedDispatcherCasesNewRouteImport
      parentRoute: typeof AuthenticatedDispatcherRoute
    }
    '/_authenticated/_dispatcher/cases/$caseId': {
      id: '/_authenticated/_dispatcher/cases/$caseId'
      path: '/cases/$caseId'
      fullPath: '/cases/$caseId'
      preLoaderRoute: typeof AuthenticatedDispatcherCasesCaseIdRouteImport
      parentRoute: typeof AuthenticatedDispatcherRoute
    }
    '/_authenticated/_crm/crm/users': {
      id: '/_authenticated/_crm/crm/users'
      path: '/crm/users'
      fullPath: '/crm/users'
      preLoaderRoute: typeof AuthenticatedCrmCrmUsersRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/_crm/crm/updates': {
      id: '/_authenticated/_crm/crm/updates'
      path: '/crm/updates'
      fullPath: '/crm/updates'
      preLoaderRoute: typeof AuthenticatedCrmCrmUpdatesRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/_crm/crm/reports': {
      id: '/_authenticated/_crm/crm/reports'
      path: '/crm/reports'
      fullPath: '/crm/reports'
      preLoaderRoute: typeof AuthenticatedCrmCrmReportsRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/_crm/crm/funeral-homes': {
      id: '/_authenticated/_crm/crm/funeral-homes'
      path: '/crm/funeral-homes'
      fullPath: '/crm/funeral-homes'
      preLoaderRoute: typeof AuthenticatedCrmCrmFuneralHomesRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/_crm/crm/export-audit': {
      id: '/_authenticated/_crm/crm/export-audit'
      path: '/crm/export-audit'
      fullPath: '/crm/export-audit'
      preLoaderRoute: typeof AuthenticatedCrmCrmExportAuditRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/_crm/crm/decedents': {
      id: '/_authenticated/_crm/crm/decedents'
      path: '/crm/decedents'
      fullPath: '/crm/decedents'
      preLoaderRoute: typeof AuthenticatedCrmCrmDecedentsRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/_crm/crm/dashboard': {
      id: '/_authenticated/_crm/crm/dashboard'
      path: '/crm/dashboard'
      fullPath: '/crm/dashboard'
      preLoaderRoute: typeof AuthenticatedCrmCrmDashboardRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/_crm/crm/cremation-logs': {
      id: '/_authenticated/_crm/crm/cremation-logs'
      path: '/crm/cremation-logs'
      fullPath: '/crm/cremation-logs'
      preLoaderRoute: typeof AuthenticatedCrmCrmCremationLogsRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/_crm/crm/cremation-logs/$logId/print': {
      id: '/_authenticated/_crm/crm/cremation-logs/$logId/print'
      path: '/$logId/print'
      fullPath: '/crm/cremation-logs/$logId/print'
      preLoaderRoute: typeof AuthenticatedCrmCrmCremationLogsLogIdPrintRouteImport
      parentRoute: typeof AuthenticatedCrmCrmCremationLogsRoute
    }
  }
}

interface AuthenticatedCrmCrmCremationLogsRouteChildren {
  AuthenticatedCrmCrmCremationLogsLogIdPrintRoute: typeof AuthenticatedCrmCrmCremationLogsLogIdPrintRoute
}

const AuthenticatedCrmCrmCremationLogsRouteChildren: AuthenticatedCrmCrmCremationLogsRouteChildren =
  {
    AuthenticatedCrmCrmCremationLogsLogIdPrintRoute:
      AuthenticatedCrmCrmCremationLogsLogIdPrintRoute,
  }

const AuthenticatedCrmCrmCremationLogsRouteWithChildren =
  AuthenticatedCrmCrmCremationLogsRoute._addFileChildren(
    AuthenticatedCrmCrmCremationLogsRouteChildren,
  )

interface AuthenticatedCrmRouteChildren {
  AuthenticatedCrmCrmCremationLogsRoute: typeof AuthenticatedCrmCrmCremationLogsRouteWithChildren
  AuthenticatedCrmCrmDashboardRoute: typeof AuthenticatedCrmCrmDashboardRoute
  AuthenticatedCrmCrmDecedentsRoute: typeof AuthenticatedCrmCrmDecedentsRoute
  AuthenticatedCrmCrmExportAuditRoute: typeof AuthenticatedCrmCrmExportAuditRoute
  AuthenticatedCrmCrmFuneralHomesRoute: typeof AuthenticatedCrmCrmFuneralHomesRoute
  AuthenticatedCrmCrmReportsRoute: typeof AuthenticatedCrmCrmReportsRoute
  AuthenticatedCrmCrmUpdatesRoute: typeof AuthenticatedCrmCrmUpdatesRoute
  AuthenticatedCrmCrmUsersRoute: typeof AuthenticatedCrmCrmUsersRoute
  AuthenticatedCrmCrmIndexRoute: typeof AuthenticatedCrmCrmIndexRoute
}

const AuthenticatedCrmRouteChildren: AuthenticatedCrmRouteChildren = {
  AuthenticatedCrmCrmCremationLogsRoute:
    AuthenticatedCrmCrmCremationLogsRouteWithChildren,
  AuthenticatedCrmCrmDashboardRoute: AuthenticatedCrmCrmDashboardRoute,
  AuthenticatedCrmCrmDecedentsRoute: AuthenticatedCrmCrmDecedentsRoute,
  AuthenticatedCrmCrmExportAuditRoute: AuthenticatedCrmCrmExportAuditRoute,
  AuthenticatedCrmCrmFuneralHomesRoute: AuthenticatedCrmCrmFuneralHomesRoute,
  AuthenticatedCrmCrmReportsRoute: AuthenticatedCrmCrmReportsRoute,
  AuthenticatedCrmCrmUpdatesRoute: AuthenticatedCrmCrmUpdatesRoute,
  AuthenticatedCrmCrmUsersRoute: AuthenticatedCrmCrmUsersRoute,
  AuthenticatedCrmCrmIndexRoute: AuthenticatedCrmCrmIndexRoute,
}

const AuthenticatedCrmRouteWithChildren =
  AuthenticatedCrmRoute._addFileChildren(AuthenticatedCrmRouteChildren)

interface AuthenticatedDispatcherRouteChildren {
  AuthenticatedDispatcherAuditLogRoute: typeof AuthenticatedDispatcherAuditLogRoute
  AuthenticatedDispatcherDashboardRoute: typeof AuthenticatedDispatcherDashboardRoute
  AuthenticatedDispatcherDriversRoute: typeof AuthenticatedDispatcherDriversRoute
  AuthenticatedDispatcherFacilitiesRoute: typeof AuthenticatedDispatcherFacilitiesRoute
  AuthenticatedDispatcherMapRoute: typeof AuthenticatedDispatcherMapRoute
  AuthenticatedDispatcherReportsRoute: typeof AuthenticatedDispatcherReportsRoute
  AuthenticatedDispatcherSettingsRoute: typeof AuthenticatedDispatcherSettingsRoute
  AuthenticatedDispatcherUsersRoute: typeof AuthenticatedDispatcherUsersRoute
  AuthenticatedDispatcherVehiclesRoute: typeof AuthenticatedDispatcherVehiclesRoute
  AuthenticatedDispatcherCasesCaseIdRoute: typeof AuthenticatedDispatcherCasesCaseIdRoute
  AuthenticatedDispatcherCasesNewRoute: typeof AuthenticatedDispatcherCasesNewRoute
  AuthenticatedDispatcherCasesIndexRoute: typeof AuthenticatedDispatcherCasesIndexRoute
}

const AuthenticatedDispatcherRouteChildren: AuthenticatedDispatcherRouteChildren =
  {
    AuthenticatedDispatcherAuditLogRoute: AuthenticatedDispatcherAuditLogRoute,
    AuthenticatedDispatcherDashboardRoute:
      AuthenticatedDispatcherDashboardRoute,
    AuthenticatedDispatcherDriversRoute: AuthenticatedDispatcherDriversRoute,
    AuthenticatedDispatcherFacilitiesRoute:
      AuthenticatedDispatcherFacilitiesRoute,
    AuthenticatedDispatcherMapRoute: AuthenticatedDispatcherMapRoute,
    AuthenticatedDispatcherReportsRoute: AuthenticatedDispatcherReportsRoute,
    AuthenticatedDispatcherSettingsRoute: AuthenticatedDispatcherSettingsRoute,
    AuthenticatedDispatcherUsersRoute: AuthenticatedDispatcherUsersRoute,
    AuthenticatedDispatcherVehiclesRoute: AuthenticatedDispatcherVehiclesRoute,
    AuthenticatedDispatcherCasesCaseIdRoute:
      AuthenticatedDispatcherCasesCaseIdRoute,
    AuthenticatedDispatcherCasesNewRoute: AuthenticatedDispatcherCasesNewRoute,
    AuthenticatedDispatcherCasesIndexRoute:
      AuthenticatedDispatcherCasesIndexRoute,
  }

const AuthenticatedDispatcherRouteWithChildren =
  AuthenticatedDispatcherRoute._addFileChildren(
    AuthenticatedDispatcherRouteChildren,
  )

interface AuthenticatedDriverRouteChildren {
  AuthenticatedDriverIndexRoute: typeof AuthenticatedDriverIndexRoute
}

const AuthenticatedDriverRouteChildren: AuthenticatedDriverRouteChildren = {
  AuthenticatedDriverIndexRoute: AuthenticatedDriverIndexRoute,
}

const AuthenticatedDriverRouteWithChildren =
  AuthenticatedDriverRoute._addFileChildren(AuthenticatedDriverRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedCrmRoute: typeof AuthenticatedCrmRouteWithChildren
  AuthenticatedDispatcherRoute: typeof AuthenticatedDispatcherRouteWithChildren
  AuthenticatedDriverRoute: typeof AuthenticatedDriverRouteWithChildren
  AuthenticatedCasesCaseIdPrintRoute: typeof AuthenticatedCasesCaseIdPrintRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCrmRoute: AuthenticatedCrmRouteWithChildren,
  AuthenticatedDispatcherRoute: AuthenticatedDispatcherRouteWithChildren,
  AuthenticatedDriverRoute: AuthenticatedDriverRouteWithChildren,
  AuthenticatedCasesCaseIdPrintRoute: AuthenticatedCasesCaseIdPrintRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PendingApprovalRoute: PendingApprovalRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
